language: node_js
node_js: lts/*

env:
  global:
    - ENCRYPTION_LABEL="c095909a09d8"

branches:
  only:
    - master

script:
  - shellcheck deploy.sh
  - npm run lint

after_success:
  - bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
